
CREATE DATABASE dbAlmacenes
GO
USE dbAlmacenes
GO

CREATE TABLE ALMACENES(
Codigo int NOT NULL,
Lugar nvarchar(100),
Capacidad int)

GO

CREATE TABLE CAJAS(
NumReferencia char(5) NOT NULL,
Contenido nvarchar(100),
Valor int,
Almacen int)

DROP TABLE  ALMACENES;

DROP TABLE CAJAS;

ALTER TABLE ALMACENES ADD CONSTRAINT PK_ALMACENCES PRIMARY KEY(Codigo);

ALTER TABLE CAJAS ADD CONSTRAINT PK_CAJAS PRIMARY KEY(NumReferencia);

ALTER TABLE CAJAS ADD CONSTRAINT FK_CAJAS FOREIGN KEY(Almacen) REFERENCES ALMACENES(Codigo);

---INSERT ALMACENES---

INSERT INTO ALMACENES VALUES(1,'Alajuela',20);

INSERT INTO ALMACENES VALUES(2,'Heredia',40);

INSERT INTO ALMACENES VALUES(3,'Cartago',50);

INSERT INTO ALMACENES VALUES(4,'San Jose',150);


---INSERT CAJAS---

INSERT INTO CAJAS VALUES(1,'Piezas Electronicas',500,1);

INSERT INTO CAJAS VALUES(2,'Refaccuibes',800,1);

INSERT INTO CAJAS VALUES(3,'Unidades de disco duro',200,1);

INSERT INTO CAJAS VALUES(4,'Piezas Electronicas',500,2);

INSERT INTO CAJAS VALUES(5,'Refaccuibes',800,3);

INSERT INTO CAJAS VALUES(6,'Unidades de disco duro',200,3);
