CREATE DATABASE dbCinema
GO
USE dbCinema
GO

CREATE TABLE SALAS(
Codigo   int NOT NULL,
Nombre   nvarchar(100),
Pelicula int)

GO

CREATE TABLE PELICULAS(
Codigo int NOT NULL,
Nombre nvarchar(100),
CalificacionEdad int)

GO

ALTER TABLE SALAS ADD PRIMARY KEY(Codigo);

ALTER TABLE PELICULAS ADD PRIMARY KEY(Codigo);

ALTER TABLE SALAS ADD FOREIGN KEY(Pelicula) REFERENCES PELICULAS(Codigo)

DROP TABLE SALAS;

DROP TABLE PELICULAS;

---INSERT PELICULAS---

INSERT INTO PELICULAS VALUES(1,'Castlelvania',18);

INSERT INTO PELICULAS VALUES(2,'Rocky Horror Picture Show',18);

INSERT INTO PELICULAS VALUES(3,'Terminator',18);

INSERT INTO PELICULAS VALUES(4,'Chucky',18);

INSERT INTO PELICULAS VALUES(5,'Back to the Future',14);

INSERT INTO PELICULAS VALUES(6,'Star Wars:A New Hope',10);

INSERT INTO PELICULAS VALUES(7,'Star Trek',10);

---INSERT SALAS---

INSERT INTO SALAS VALUES(1,'SALA A',1);

INSERT INTO SALAS VALUES(2,'SALA B',2);

INSERT INTO SALAS VALUES(3,'SALA C',3);

INSERT INTO SALAS VALUES(4,'SALA D',4);

INSERT INTO SALAS VALUES(5,'SALA E',5);

INSERT INTO SALAS VALUES(6,'SALA F',6);

INSERT INTO SALAS VALUES(7,'SALA G',NULL);