CREATE DATABASE dbDespachos
GO
USE dbDespachos
GO

CREATE TABLE DIRECTORES(
DNI varchar(8) NOT NULL,
NomApels nvarchar(255),
DNIJefe varchar(8),
Despacho int)

GO

CREATE TABLE DESPACHOS(
Numero int NOT NULL,
Capacidad int)

GO

ALTER TABLE DIRECTORES ADD CONSTRAINT PK_DIRECTORES PRIMARY KEY(DNI);

ALTER TABLE DESPACHOS ADD CONSTRAINT PK_DESPACHOS PRIMARY KEY(Numero);

ALTER TABLE DIRECTORES ADD CONSTRAINT FK_DIRECTOR_JEFE FOREIGN KEY(DNIJefe) REFERENCES DIRECTORES(DNI);

ALTER TABLE DIRECTORES ADD CONSTRAINT FK_DIRECTOR_DESPACHO FOREIGN KEY(Despacho) REFERENCES DESPACHOS(Numero)

---INSERT DESPACHOS---

INSERT INTO DESPACHOS VALUES(1,20);

INSERT INTO DESPACHOS VALUES(2,12);

INSERT INTO DESPACHOS VALUES(3,15);


---INSERT DIRECTORES---

INSERT INTO DIRECTORES VALUES('01','Joan Sebastian',NULL,1);

INSERT INTO DIRECTORES VALUES('02','Vicente Fernandez','01',1);

INSERT INTO DIRECTORES VALUES('03','Bernie Sanders','01',1);

INSERT INTO DIRECTORES VALUES('04','Cindy Sanders',NULL,2);

INSERT INTO DIRECTORES VALUES('05','Jason Sanders','04',2);

INSERT INTO DIRECTORES VALUES('06','Nikki Mirage','05',2);

INSERT INTO DIRECTORES VALUES('07','Kelly Clarkson','05',2);

INSERT INTO DIRECTORES VALUES('08','Eduard Henderson',NULL,2);

INSERT INTO DIRECTORES VALUES('74568521','Peter Sellers',NULL,2);
