CREATE DATABASE dbEmpleadosDepartamentos
GO
USE dbEmpleadosDepartamentos
GO

CREATE TABLE EMPLEADOS(
DNI varchar(8) NOT NULL,
Nombre nvarchar(100),
Apellidos nvarchar(255),
Departamento int)

GO

CREATE TABLE DEPARTAMENTOS(
Codigo int NOT NULL,
Nombre nvarchar(100),
Presupuesto int)

GO

DROP TABLE EMPLEADOS;

DROP TABLE DEPARTAMENTOS;

ALTER TABLE DEPARTAMENTOS ADD CONSTRAINT PK_DEPAPARTAMENTOS PRIMARY KEY(Codigo);

ALTER TABLE EMPLEADOS ADD CONSTRAINT PK_EMPLEADOS PRIMARY KEY(DNI);

ALTER TABLE EMPLEADOS ADD CONSTRAINT FK_EMPLEADOS_DEPARTAMENTOS FOREIGN KEY(Departamento) REFERENCES DEPARTAMENTOS(Codigo);

---INSERT DEPARTAMENTOS---

INSERT INTO DEPARTAMENTOS VALUES(1,'Informatica',20000);

INSERT INTO DEPARTAMENTOS VALUES(2,'Publicidad',60000);

INSERT INTO DEPARTAMENTOS VALUES(3,'Soporte Tecnico',80000);


---INSERT EMPLEADOS---

INSERT INTO EMPLEADOS VALUES('0001','James','Brown',1);

INSERT INTO EMPLEADOS VALUES('0002','Jonny','Cash',1);

INSERT INTO EMPLEADOS VALUES('0003','Willie','Nelson',1);

INSERT INTO EMPLEADOS VALUES('0004','Bobby','Cyrus',2);

INSERT INTO EMPLEADOS VALUES('0005','Tonny','Montana',3);

INSERT INTO EMPLEADOS VALUES('0006','Jaimee','Curtis',3);
